on:
  repository_dispatch:
    types: build-data

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
    - run: npx -y -p sill-api@latest build-data
      env:
        DATA_REPO_SSH_URL: ${{github.event.client_payload.dataRepoSshUrl}}
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        INCREMENTAL: ${{github.event.client_payload.incremental}}
