name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  poke_sill-publish:
   runs-on: ubuntu-latest
   steps:
   - uses: peter-evans/repository-dispatch@v1
     with:
       token: ${{ secrets.PAT }}
       event-type: publish_data
       repository: garronej/sill-publish
