name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  poke_gitops:
   runs-on: ubuntu-latest
   needs: release
   steps:
   - uses: peter-evans/repository-dispatch@v1
     with:
       token: ${{ secrets.PAT }}
       event-type: publish_data
       repository: etalab/sill-publish
