on:
  repository_dispatch:
    types: data_updated

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: actions/setup-node@v2.1.3
    - uses: bahmutov/npm-install@v1
    - run: yarn build
    - run: yarn build-data etalab/sill-data
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/etalab/sill-data.git
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    - run: npx -y -p gh-pages@3.0.0 gh-pages -b build -d data/build -u "github-actions-bot <actions@github.com>"
    - uses: appleboy/scp-action@v0.1.2
      with:
        host: 193.70.86.67
        username: web
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "data/build/compiledData_withoutReferents.json"
        target: "~/websites/code.gouv.fr/data/sill3.json"
