on:
  repository_dispatch:
    types: data_updated

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: actions/setup-node@v2.1.3
    - uses: bahmutov/npm-install@v1
    - run: yarn build
    - run: yarn build-data etalab/sill-data
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/etalab/sill-data.git
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    - run: npx -y -p gh-pages@3.0.0 gh-pages -b build -d data/build -u "github-actions-bot <actions@github.com>"
    - uses: appleboy/scp-action@v0.1.2
      with:
        host: 193.70.86.67
        username: web
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "data/build/compiledData_withoutReferents.json"
        target: "~/websites/code.gouv.fr/data/sill3.json"

  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Show envs
        run: env
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"