on:
  repository_dispatch:
    types: compile-data

jobs:
  build-data:
    runs-on: ubuntu-latest
    env: 
      DATA_REPOSITORY: ${{ github.event.client_payload.repository }}
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: actions/setup-node@v2.1.3
    - uses: bahmutov/npm-install@v1
    - run: yarn build
    - run: node dist/bin/build-data.js $DATA_REPOSITORY incremental=$INCREMENTAL
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        INCREMENTAL: ${{ github.event.client_payload.incremental }}
    - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${DATA_REPOSITORY}.git
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
    - run: npx -y -p gh-pages@3.0.0 gh-pages -b build -d data/build -u "github-actions-bot <actions@github.com>"
    - if: github.event.client_payload.repository != 'etalab/sill-data'
      run: exit 0
    - run: cp data/build/compiledData_withoutReferents.json sill-data.json
    - uses: appleboy/scp-action@v0.1.2
      with:
        host: 193.70.86.67
        username: web
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "sill-data.json"
        target: "~/websites/code.gouv.fr/data/"